services:
  atsenergobot:
    build: .
    container_name: atsenergobot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?Не задан TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:?Не задан TELEGRAM_CHAT_ID}
